name: Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build
      run: mvn compile

    - name: Run and Collect coverage
      run: mvn test jacoco:report

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: ./target/site/jacoco
        retention-days: 7